### ISSUE TITLE
Feature: Display number of entries stored in the log

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/clippy#1]
The name says it all. Just a simple <p> in the render process to display the number of entries in the log.

**Comment by bywasik** [comment]
@KL13NT can you review this, please?

**Comment by KL13NT** [comment]
Implemented in #7 
Thanks for working on this, @iamkacperwasik. Feel free to check other issues as well!

**Comment by KL13NT** [comment]
Just saw that you're a student so wanted to give you a few tips, hope you don't mind! @iamkacperwasik 

A few things to note for other projects/future contributions, it's usually worth looking around for a contribution guide and other documents of the sorts. I don't have any for this project since it was really tiny and more on the experimental side, but open source projects usually have those documents. An example of this (from my other projects) is [Pollu](https://github.com/KL13NT/pollu/blob/master/CONTRIBUTING.md).

Replying to the issue and asking for assignment before working on it is also another thing to keep in mind. The maintainers might have forgotten to assign the person working on the issue on GH, and they may end up not seeing the issue as worth the effort. So, to avoid losing your efforts and to stand on 100% clear grounds you should always reply to the issue before working on it.

**Comment by bywasik** [comment]
Thank you for your tips, I would definitely use them in my future contributions
