### ISSUE TITLE
Feature: Keyboard shortcuts

### ISSUE THREAD

**Issue by KL13NT** [KL13NT/clippy#17]
The following shortcuts would make it easier to manage the clipboard:
- `CTRL + DELETE` - clear clipboard
- `SELECT MULTIPLE + DELETE` - delete selected entries
- `SELECT MULTIPLE + CTRL + C` - copy selected entries
- `CTRL + SHIFT + DELETE` - clear log

This could be implemented in two stages
- [x] Add general listeners for shortcuts
- ~Add an options page to manage these shortcuts~

**Comment by bywasik** [comment]
Can you assign me to this issue? @KL13NT

**Comment by KL13NT** [comment]
Sure, @iamkacperwasik! How are you gonna implement it?

**Comment by bywasik** [comment]
I would use event listener or even simpler [iohook](https://wilix-team.github.io/iohook/)

**Comment by KL13NT** [comment]
I'd rather not install more dependencies, at least not until I refactor the codebase well enough. Let's keep it simple, in the `render.js` process, and using simple event listeners. Assigning it to you.

**Comment by iamkacperwasik** [comment]
Is doing commit after any small change, e.g. add CTRL + DELETE shortcut a good in this project?

**Comment by bywasik** [comment]
Is doing commits after any small change, e. g. adding CTRL + DELETE shortcut is good in this project?

**Comment by KL13NT** [comment]
You can do that. I can then squash them into a single commit before merging to avoid polluting the repo's history too much.

**Comment by bywasik** [comment]
how should I implement shortcut management?

**Comment by KL13NT** [comment]
@iamkacperwasik Shortcut management will be implemented in the next version when #30 is implemented. By then we'd have a fully functional settings page and would have the settings storage logic setup.

**Comment by bywasik** [comment]
I have implemented some kind of helper for creating page  in my latest commit on in this [pr](https://github.com/KL13NT/clippy/pull/28). Should I remove it then?
