### ISSUE TITLE
🧩 Feature: Search bar

### ISSUE THREAD

**Issue by bywasik** [KL13NT/clippy#26]

**Comment by KL13NT** [comment]
How could it be implemented?

**Comment by bywasik** [comment]
I was thinking about something like:

<img src="https://user-images.githubusercontent.com/57839948/107634192-711ca280-6c69-11eb-8d5c-ab4d9eff16f4.png" width="500px">

It would be something like a filter. There will be an option to change if you like to search for a specific text or search only for images that fits selected format.

**Comment by KL13NT** [comment]
That sounds awesome. Searching for things in a long log is certainly something I'd love. I'll come up with the design for it and we can work on it after.

**Comment by KL13NT** [comment]
Marking it as *blocked for design*.

**Comment by KL13NT** [comment]
I won't be available (because of exams) for a few days. You may assign to this without any visual design and when the design is finally ready we can integrate it.

**Comment by bywasik** [comment]
I can try to implement the logic. **Good luck on exams, by the way.**

**Comment by KL13NT** [comment]
Thanks! :D 

Here's a few tips:
- Use labels like GitHub. `image: png` to search for PNG images, `text: some text` to search for `some text` in the history of text entries. If the user doesn't specify a type (e.g. writes `some text` immediately) search for text by default.
- Remember that each entry has a `type` which is the interpreted type (`image` or `text`), and a `_type` which is the full MIME type such as `image/png` or `image/jpg`. This would make your logic easier. https://github.com/KL13NT/clippy/blob/7d532d69b9d34ff327180ee44ed918611b63967d/src/types/entry.js#L7-L8

**Comment by KL13NT** [comment]
How's the progress on this one?

**Comment by bywasik** [comment]
My operating system with all the work broke this morning 😢

**Comment by KL13NT** [comment]
Oh, sorry to hear that! Did you push to your fork or is the work *gone*?

**Comment by bywasik** [comment]
it's all gone, but it's easy to rewrite

**Comment by KL13NT** [comment]
I merged the PR right now! Good work! 😄
I'll add the styling right away as well.

**Comment by bywasik** [comment]
Should be closed now by the https://github.com/KL13NT/clippy/commit/a2052e38a23c32b6186658ac65548fbf62395884
