### ISSUE TITLE
🐛 Bug:  program lag and drains computer CPU when you copy .jpg file

### ISSUE THREAD

**Issue by bywasik** [KL13NT/clippy#52]
**Describe the bug**
When you copy some image that is .jpg, Clippy starts to lag and drains computer cpu.

**To Reproduce**
1. copy repo
2. `npm run dev` or `npm run make`
3. start the program
4. copy any image from google
5. see whats happening

**Screenshots**
![image](https://user-images.githubusercontent.com/57839948/108492618-ab0f2980-72a5-11eb-9fe7-0216af922b7b.png)
![image](https://user-images.githubusercontent.com/57839948/108496016-d09e3200-72a9-11eb-9a16-cec1ae097a0b.png)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.10 64bit]
 - Version [e.g. Clippy@2.0.0]

**Comment by bywasik** [comment]
example: https://upload.wikimedia.org/wikipedia/commons/4/41/Sunflower_from_Silesia2.jpg

**Comment by bywasik** [comment]
Turns out, it only happens when you copy image with high resolution

**Comment by KL13NT** [comment]
High resolution images take a lot of space when copying, let alone converting them to base64 strings to store them. NodeJS adds a lot of overhead when converting buffers to strings, which is expected. I'll look more into it and perhaps come up with some other solution in my free time. In the meanwhile, feel free to give more input!

**Comment by KL13NT** [comment]
Just noticed you have multiple Clippy instances running. Mind keeping one only and benchmark that?

**Comment by KL13NT** [comment]
Okay so, we could replace the base64 thing with a Blob, and generate a Blob URL for it on the renderer process. This would eliminate the CPU usage completely as there wouldn't there be a need for transforming anything. I'll give it a shot after my exam.

Edit: We'd have to serialize it either way before using IPC so it'd still be useless. Closing until a better idea comes up.
